### ISSUE TITLE
Jest test fails with parsing error

### ISSUE THREAD

**Issue by danielmcquillen** [ScienceCommunicationLab/KinesinLMS#5]
**Describe the bug**
`npm test` fails because Jest is having trouble parsing certain typescript files.

**To Reproduce**
Run `npm_test`

The following errors occur:

```
 FAIL  kinesinlms_components/src/diagram/utils/DiagramChangeDetector.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/danielmcquillen/projects/ibio/v2/pardalote_project/kinesinlms/node_modules/jsondiffpatch/lib/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import DiffPatcher from './diffpatcher.js';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import { DiagramModel } from '@projectstorm/react-diagrams';
      2 | import stringify from 'fast-json-stable-stringify'
    > 3 | import { create as createJsonDiffPatcher, DiffPatcher } from 'jsondiffpatch';
        | ^
      4 |
      5 | export default class DiagramChangeDetector {
      6 |     private readonly normalizedInitialModel: object;

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1505:14)
      at Object.<anonymous> (kinesinlms_components/src/diagram/utils/DiagramChangeDetector.ts:3:1)
      at Object.<anonymous> (kinesinlms_components/src/diagram/utils/DiagramChangeDetector.test.ts:1:1)

 FAIL  kinesinlms_components/src/tabletool/TableTool.test.tsx
  ● Test suite failed to run

    Cannot find module 'msw/node' from 'kinesinlms_components/src/tabletool/TableTool.test.tsx'

    > 1 | import { setupServer } from 'msw/node';
        | ^
      2 | import { http, HttpResponse } from 'msw';
      3 | import { act, fireEvent, render, screen, waitFor } from '@testing-library/react';
      4 | import React from 'react';

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.<anonymous> (kinesinlms_components/src/tabletool/TableTool.test.tsx:1:1)
```

**Expected behavior**
Tests should complete.

**Comment by danielmcquillen** [comment]
Addressed in #9
